package resercas;
// Generated 13-jun-2018 15:07:48 by Hibernate Tools 5.2.10.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Cliente generated by hbm2java
 */
public class Cliente implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idcli;
	private String nombre;
	private String mail;
	private String password;
	private Set<Reserva> reservas = new HashSet<Reserva>(0);

	public Cliente() {
	}

	public Cliente(String nombre, String mail, String password) {
		this.nombre = nombre;
		this.mail = mail;
		this.password = password;
	}

	public Cliente(String nombre, String mail, String password, Set<Reserva> reservas) {
		this.nombre = nombre;
		this.mail = mail;
		this.password = password;
		this.reservas = reservas;
	}

	public Integer getIdcli() {
		return this.idcli;
	}

	public void setIdcli(Integer idcli) {
		this.idcli = idcli;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getMail() {
		return this.mail;
	}

	public void setMail(String mail) {
		this.mail = mail;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public Set<Reserva> getReservas() {
		return this.reservas;
	}

	public void setReservas(Set<Reserva> reservas) {
		this.reservas = reservas;
	}

}
