package resercas;
// Generated 13-jun-2018 15:07:48 by Hibernate Tools 5.2.10.Final

import java.util.Date;

/**
 * Reserva generated by hbm2java
 */
public class Reserva implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idreserva;
	private Cliente cliente;
	private Empleado empleado;
	private Habitacion habitacion;
	private Date fechaIni;
	private Date fechaFin;
	private String estado;

	public Reserva() {
	}

	public Reserva(Cliente cliente, Empleado empleado, Habitacion habitacion, Date fechaIni, Date fechaFin,String estado) {
		this.cliente = cliente;
		this.empleado = empleado;
		this.habitacion = habitacion;
		this.fechaIni = fechaIni;
		this.fechaFin = fechaFin;
		this.estado = estado;
	}
	
	public Reserva(Cliente cliente, Habitacion habitacion, Date fechaIni, Date fechaFin,String estado) {
		this.cliente = cliente;		
		this.habitacion = habitacion;
		this.fechaIni = fechaIni;
		this.fechaFin = fechaFin;
		this.estado = estado;
	}
	
	public Integer getIdreserva() {
		return this.idreserva;
	}

	public void setIdreserva(Integer idreserva) {
		this.idreserva = idreserva;
	}

	public Cliente getCliente() {
		return this.cliente;
	}

	public void setCliente(Cliente cliente) {
		this.cliente = cliente;
	}

	public Empleado getEmpleado() {
		return this.empleado;
	}

	public void setEmpleado(Empleado empleado) {
		this.empleado = empleado;
	}

	public Habitacion getHabitacion() {
		return this.habitacion;
	}

	public void setHabitacion(Habitacion habitacion) {
		this.habitacion = habitacion;
	}

	public Date getFechaIni() {
		return this.fechaIni;
	}

	public void setFechaIni(Date fechaIni) {
		this.fechaIni = fechaIni;
	}

	public Date getFechaFin() {
		return this.fechaFin;
	}

	public void setFechaFin(Date fechaFin) {
		this.fechaFin = fechaFin;
	}

	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

}
