package resercas;
// Generated 16-jun-2018 20:52:08 by Hibernate Tools 5.2.10.Final

import java.sql.Date;

/**
 * Reserva generated by hbm2java
 */
public class Reserva implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idreserva;
	private Cliente cliente;
	private Empleado empleado;
	private Habitacion habitacion;
	private Date fechaIni;
	private Date fechaFin;
	private double total;

	public Reserva() {
	}

	public Reserva(Cliente cliente, Habitacion habitacion, Date fechaIni, Date fechaFin,
			double total, Empleado empleado) {
		this.cliente = cliente;
		this.empleado = empleado;
		this.habitacion = habitacion;
		this.fechaIni = fechaIni;
		this.fechaFin = fechaFin;
		this.total = total;
	}
	public Reserva(Cliente cliente, Habitacion habitacion, Date fechaIni, Date fechaFin, double total) {
		this.cliente = cliente;		
		this.habitacion = habitacion;
		this.fechaIni = fechaIni;
		this.fechaFin = fechaFin;
		this.total = total;
	}
	public Integer getIdreserva() {
		return this.idreserva;
	}

	public void setIdreserva(Integer idreserva) {
		this.idreserva = idreserva;
	}

	public Cliente getCliente() {
		return this.cliente;
	}

	public void setCliente(Cliente cliente) {
		this.cliente = cliente;
	}

	public Empleado getEmpleado() {
		return this.empleado;
	}

	public void setEmpleado(Empleado empleado) {
		this.empleado = empleado;
	}

	public Habitacion getHabitacion() {
		return this.habitacion;
	}

	public void setHabitacion(Habitacion habitacion) {
		this.habitacion = habitacion;
	}

	public Date getFechaIni() {
		return this.fechaIni;
	}

	public void setFechaIni(Date fechaIni) {
		this.fechaIni = fechaIni;
	}

	public Date getFechaFin() {
		return this.fechaFin;
	}

	public void setFechaFin(Date fechaFin) {
		this.fechaFin = fechaFin;
	}

	public double getTotal() {
		return this.total;
	}

	public void setTotal(double total) {
		this.total = total;
	}

}
